language: scala

services:
- docker

jdk: oraclejdk8

scala:
- 2.12.6

env:
  matrix:
    - secure: R8cJiyTBbOsTbc5PltGO5FMhwXhWWtfWmt5S1wShhez3Z0jAif4kn21qAgOYuGB0QKWh/0iu3JWVwPznInm0MpxaWmTfU6Bkgni5dPJyZwrLB1IwJUi4PTQu9jObvay/JcNM/2pPWdZxK+Qj/p9VTOK2ciCneCRdHPuUD1pOoA/cm0oLqh08fKEELl9ObyVDeR+U+5O7q7xU5L03TtbdNMrbooSIH7/PSZZ1QWNGORKojYXL9DeUfANSTvNFfU/Iadq4WnQp8kWrA79EeqjdbT8+cbbdwqVXKzyNi2sQueHFnlUmC9YacGLxplK5dLN2NS94ohP85emoPdvwuNCHsVKKNzOISrwVYuB8W3O+8u6qRXbglNzeTzS04LWgWjHIdQLOb31tBnfcFmC2pxnvrgaSMwDsJvSOgmzkBOnikOCPn9tzg3Jsa9RGOYPoqNVc3EEaSI3F3huuPErs8FeShdCKNU02+wy2lWwCtyXlzpKwwi8lwa3yNVEdfAS2fJvbjYHysW1lYK19FXlk5uf2bSzKgRC384d19gnBV9o2GopbNz7OTovyQtNgoMesUAIWZaGC3L5BwhyT+uJm+bAyKl/ROJdN39dpYfKoHvD3EujWJHd8B6BQRsKUqoiPNLKs3CWeAvEJTX+nC6tGDSeWstVJE8nANUHS0K1lfSiqvOs=
    - secure: aH3rAM3w3DmwNmQMT/xZ9i+6MsnpDfmkyny6N2Fy0qK5CrcX6NARitL6eoA/r+eI3bB1gcu92dI0pyeWOCyxFYQoBsQYF/5FLeR1lYu4gbgE+4nNCixkU+GDOMzC+aQnQkHIlYTok6GiGQOSh218/E7krQ+FEpWvEcag+IhTf+yNySqPpc8ZKtZgxLAvWiI0EkegMzIlU7e7hmvrhgVduE2LKhHUbzHN1lC/lzPwT2sTNohxjDEG1A+I11z+CZKZmfOUxGG8hOnEuVVwfcccBu4uz5vHFruhomBipOvPN5M8579Z4eEKQV6UKOjy8QxQx7Hs0T+mYN5dcGaXz6hRyvsQ20HBRkprc9H0Y+1W9gWPj1xNUCj2/KV/oO9DVuDJbA6U59xJt1QquUc31jS8nrrEUPPB3yNeC72itp2MnlHHlt1FOvOCbxFBlg1NXxpBLj4gGlB5A624rsW4FCd+8yYgbfs7+m7xwU87A4zOpvshSjqqwFooa+BBYmrEZnw9bHmND9XV4wpGf+zCe2jpvdLXn+/1NG7HIrMXUZnekQI/FgR46AuMm92qr9XyHA4ch8LUieHr0ny/su7J9ll3yUaXsl0iFNMiPtOdhs33yLHwkRpV1sGyO6luiBksXCPuNIy1bx2A0U3sblPvdq8bCkEEiLVxVUErnSmOJSYVHno=

deploy:
  provider: script
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - sbt docker:publish
  on:
    all_branches: true
#    branch: master

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
