sudo: required
language: scala
scala:
  - 2.12.6
jdk: oraclejdk8

services:
  - docker

before_deploy: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

deploy:
  provider: script
  script: sbt docker:publish
  on:
    branch: master
    tags: true

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt